import type { Job } from './model';
const rows = [
  [
    'Coordinatrice d’ateliers culturels',
    'Maison des Horizons',
    'Culture & lien social',
    'CDI',
    '28–32 k€ brut / an',
    'Imaginer des rendez-vous qui rassemblent. Organiser les ateliers, accueillir les participants et accompagner les intervenants.',
    ['organiser', 'accueillir', 'creer'],
    false,
    true,
  ],
  [
    'Conseillère en librairie',
    'Les Pages Ouvertes',
    'Livres & découverte',
    'CDI',
    'Salaire non renseigné',
    'Écouter les envies des lecteurs, partager vos découvertes et faire vivre une librairie de quartier.',
    ['accueillir', 'vendre', 'creer'],
    false,
    true,
  ],
  [
    'Assistante de projet associatif',
    'Les Liens Communs',
    'Vie associative',
    'CDD',
    '2 100 € brut / mois',
    'Donner un coup de main aux projets locaux : préparer les événements, suivre les inscriptions et coordonner les bénévoles.',
    ['organiser', 'aider', 'analyser'],
    false,
    false,
  ],
  [
    'Fleuriste en atelier',
    'Atelier Saison',
    'Artisanat & végétal',
    'CDI',
    '1 900–2 200 € brut / mois',
    'Composer des bouquets, préparer les fleurs et conseiller les clients au fil des saisons.',
    ['manuel', 'creer', 'nature'],
    false,
    true,
  ],
  [
    'Chargée d’accueil en musée',
    'Musée des Récits',
    'Culture & patrimoine',
    'CDD',
    'Salaire non renseigné',
    'Accueillir les visiteurs, rendre les collections accessibles et accompagner les groupes dans leur découverte.',
    ['accueillir', 'aider'],
    false,
    true,
  ],
  [
    'Assistante de gestion',
    'Studio Commun',
    'Organisation & gestion',
    'CDI',
    '26–30 k€ brut / an',
    'Faciliter le quotidien d’une petite équipe : suivre les dossiers, préparer les rendez-vous et organiser les informations.',
    ['organiser', 'analyser'],
    false,
    false,
  ],
  [
    'Animatrice nature',
    'Les Sentiers Verts',
    'Environnement',
    'CDD',
    '1 950 € brut / mois',
    'Faire découvrir la biodiversité et préparer des activités dehors pour petits et grands.',
    ['nature', 'aider', 'creer'],
    false,
    true,
  ],
  [
    'Technicienne cycles',
    'La Roue Libre',
    'Mobilité & artisanat',
    'CDI',
    '24–28 k€ brut / an',
    'Diagnostiquer les petites pannes, réparer les vélos et aider chacun à reprendre la route.',
    ['manuel', 'analyser', 'aider'],
    false,
    false,
  ],
  [
    'Conseillère en insertion',
    'Cap Demain',
    'Accompagnement',
    'CDI',
    '27–31 k€ brut / an',
    'Écouter les parcours, identifier les prochaines étapes et accompagner les personnes vers leurs projets.',
    ['aider', 'accueillir', 'organiser'],
    true,
    false,
  ],
  [
    'Assistante qualité',
    'Fabrique Locale',
    'Analyse & production',
    'CDI',
    '25–29 k€ brut / an',
    'Observer les processus, vérifier les produits et proposer des améliorations concrètes avec l’équipe.',
    ['analyser', 'manuel'],
    false,
    false,
  ],
  [
    'Employée de jardin partagé',
    'Les Jardins Communs',
    'Environnement',
    'CDD',
    'Salaire non renseigné',
    'Entretenir les espaces, cultiver les plantations et accompagner les activités du jardin.',
    ['nature', 'manuel', 'aider'],
    false,
    false,
  ],
  [
    'Chargée de communication',
    'Studio Passage',
    'Communication',
    'CDD',
    '28–33 k€ brut / an',
    'Raconter les projets, préparer des contenus et coordonner les publications de la structure.',
    ['creer', 'organiser'],
    true,
    false,
  ],
] as const;
export const demoJobs: Job[] = rows.map((r, i) => ({
  id: `demo-${i + 1}`,
  title: r[0],
  company: r[1],
  sector: r[2],
  contract: r[3],
  salary: r[4],
  summary: r[5],
  description: `${r[5]}\n\nCet exemple est fictif et sert uniquement à découvrir le fonctionnement de JobDiscover. Il ne permet pas de candidater.`,
  tags: [...r[6]],
  experienceRequired: r[7],
  weekend: r[8],
  night: false,
  city: 'Lyon',
  lat: 45.764 + (i % 3) * 0.02,
  lon: 4.835 + (i % 4) * 0.02,
  url: null,
  updatedAt: '2026-09-01T00:00:00Z',
  active: true,
  demo: true,
}));
