import { AppError } from '../validation.ts';
export { AppError } from '../validation.ts';
export type Config=Record<string,string|undefined>;
export async function config():Promise<Config>{let bindings:Config={};try{const runtime=await import('cloudflare:workers');bindings=runtime.env as unknown as Config;}catch{}return {...process.env,...bindings};}
export function configured(c:Config){return Boolean(c.SUPABASE_URL&&c.SUPABASE_PUBLISHABLE_KEY&&c.SUPABASE_SECRET_KEY&&c.APP_ORIGIN);}
export const securityHeaders={'Cache-Control':'private, no-store, max-age=0','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Vary':'Cookie'};
export function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...securityHeaders,'Content-Type':'application/json; charset=utf-8'}});}
export function assertOrigin(req:Request,c:Config){if(!c.APP_ORIGIN||req.headers.get('origin')!==new URL(c.APP_ORIGIN).origin)throw new AppError(403,'Requête non autorisée.');if(req.headers.get('sec-fetch-site')==='cross-site')throw new AppError(403,'Requête non autorisée.');}
export async function body(req:Request){if(!req.headers.get('content-type')?.startsWith('application/json'))throw new AppError(415,'Format attendu : JSON.');const length=Number(req.headers.get('content-length')??0);if(length>16384)throw new AppError(413,'Requête trop volumineuse.');const reader=req.body?.getReader();if(!reader)throw new AppError(400,'Données manquantes.');let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>16384){await reader.cancel();throw new AppError(413,'Requête trop volumineuse.');}chunks.push(value);}const all=new Uint8Array(size);let offset=0;for(const ch of chunks){all.set(ch,offset);offset+=ch.length;}try{return JSON.parse(new TextDecoder().decode(all));}catch{throw new AppError(400,'Données invalides.');}}
export async function remote(url:string,init:RequestInit={}){try{return await fetch(url,{...init,signal:AbortSignal.timeout(12000),cache:'no-store'});}catch{throw new AppError(503,'Le service est momentanément indisponible. Réessaie dans un instant.');}}
export function db(c:Config,path:string,token:string,init:RequestInit={}){return remote(`${c.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY!,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...init.headers}});}
export function admin(c:Config,path:string,init:RequestInit={}){return remote(`${c.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:c.SUPABASE_SECRET_KEY!,Authorization:`Bearer ${c.SUPABASE_SECRET_KEY}`,'Content-Type':'application/json',...init.headers}});}
export async function requireOK(r:Response){if(!r.ok)throw new AppError(503,'Impossible d’enregistrer ou de charger les données pour le moment.');}
export async function authFetch(c:Config,path:string,data?:unknown,token?:string,method='POST'){return remote(`${c.SUPABASE_URL}/auth/v1/${path}`,{method,headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY!,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(data!==undefined?{body:JSON.stringify(data)}:{})});}
export function readCookie(req:Request,name:string){return req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1)||'';}
function cookieName(c:Config,name:string){return c.APP_ORIGIN?.startsWith('https:')?`__Host-jd_${name}`:`jd_${name}`;}
export function sessionCookies(r:Response,c:Config,session?:{access_token:string;refresh_token:string;expires_in?:number}){const secure=c.APP_ORIGIN?.startsWith('https:')?'; Secure':'';for(const [name,value,age] of [['access',session?.access_token||'',session?Math.min(session.expires_in||3600,3600):0],['refresh',session?.refresh_token||'',session?60*60*24*7:0]] as const){r.headers.append('Set-Cookie',`${cookieName(c,name)}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}${secure}`);}return r;}
export type Session={id:string;email:string;token:string};
export async function authenticate(req:Request,c:Config):Promise<Session>{if(!configured(c))throw new AppError(503,'Les comptes seront disponibles après la configuration du service. Tu peux explorer la démonstration.');const token=readCookie(req,cookieName(c,'access'));if(!token)throw new AppError(401,'Connecte-toi pour retrouver ton espace.');const r=await authFetch(c,'user',undefined,token,'GET');if(!r.ok)throw new AppError(401,'Ta session a expiré. Reconnecte-toi.');const u=await r.json() as {id:string;email:string;email_confirmed_at?:string};if(!u.id||!u.email_confirmed_at)throw new AppError(401,'Confirme ton adresse e-mail pour continuer.');return {id:u.id,email:u.email,token};}
export function refreshCookie(req:Request,c:Config){return readCookie(req,cookieName(c,'refresh'));}
export async function limit(c:Config,key:string,max:number,seconds:number){const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key)))).map(x=>x.toString(16).padStart(2,'0')).join('');const r=await admin(c,'rpc/consume_rate_limit',{method:'POST',body:JSON.stringify({bucket_key:digest,max_hits:max,window_seconds:seconds})});await requireOK(r);if(await r.json()!==true)throw new AppError(429,'Un peu trop de tentatives. Réessaie dans quelques minutes.');}
